version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      allow:
          - dependency-type: all
      schedule:
          interval: monthly
          time: "03:00"
      open-pull-requests-limit: 10
      pull-request-branch-name:
          separator: "-"
      reviewers: [TamasSzigeti]
    - package-ecosystem: composer
      directory: /
      versioning-strategy: increase-if-necessary
      allow:
          - dependency-type: all
      schedule:
          interval: monthly
          time: "03:00"
      pull-request-branch-name:
          separator: "-"
      reviewers: [TamasSzigeti]
